version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      image: scrapinghub/scrapinghub-stack-scrapy
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t $image .

      - deploy:
          name: Push Docker image to DockerHub
          command: |
            set -x
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

            tags="$(git tag -l --points-at ${CIRCLE_SHA1})"

            [[ "${CIRCLE_BRANCH:0:7}" == "branch-" ]] && tags="$tags ${CIRCLE_BRANCH:7}-latest"
            [[ "${CIRCLE_BRANCH}" == "master" ]] && tags="$tags latest"

            if [ -n "$tags" ]; then 
              set -e

              for tag in $tags; do
                repo=$image:$tag
                docker tag $image $repo
                docker push $repo
              done
            fi

            # Extract debug info and store in S3
            set -e

            tmpfile=$(mktemp)

            cleanup() {
              rm -rf "$tmpfile"
            }
            trap cleanup EXIT
            apk update && apk add --no-cache jq

            docker run --rm $image shub-image-info --debug | tee shub-debug.json
            cat shub-debug.json | jq -r ".debug" | tee $tmpfile

            for tag in $tags; do
              docker run -it -v ${tmpfile}:/debug_file.txt d3fk/s3cmd:arch-stable \
                --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_ACCESS_KEY \
                put /debug_file.txt s3://${S3_BASE}/$tag
            done
